spring.application.name=Spring_Security_JWT_App-1

spring.datasource.url=jdbc:mysql://localhost:3306/remindflow
spring.datasource.username=root
spring.datasource.password=TIGER

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080



spring.mail.host=smtp.gmail.com
spring.mail.port=587
#Adding dummy value ---------------------
spring.mail.username=your_email_here
spring.mail.password=your_app_password_here
jwt.secret=YOUR_SECRET_KEY

#-----------------------------------------
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
